#!/bin/sh
BUCKET=r20.sunrun.com

aws s3 sync dist/prod s3://$BUCKET \
  --exclude '*' \
  --include '*.js' --include '*.html' --include '*.tmpl' --include '*.css' --include '*.ttf' \
  --include 'tourLocationSets.json' \
  --include 'faqcards.json' \
  --include 'properties.json' \
  --include 'branches.json' \
  --include 'leadOrganizations.json' \
  --include 'vendor/**/*' \
  --include '*.jpg' --include '*.png' \
  --region us-west-1 --acl public-read \
  --profile r20prod \
  --delete
