#!/bin/sh
BUCKET=r20.sunrundev.com

aws s3 sync dist/staging s3://$BUCKET \
  --exclude '*' \
  --include '*.js' --include '*.html' --include '*.tmpl' --include '*.css' --include '*.ttf' \
  --include 'tourLocationSets.json' \
  --include 'faqcards.json' \
  --include 'properties.json' \
  --include 'branches.json' \
  --include 'leadOrganizations.json' \
  --include 'vendor/**/*' \
  --include '*.jpg' --include '*.png' \
  --region us-west-1 --acl public-read \
  --profile pivotaldev \
  --delete